# The URL the site will be built for
base_url = "https://bharadwajraju.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

taxonomies = [
  { name = "category", feed = false, render = false }
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
smart_punctuation = true

[markdown.highlighting]
style = "class"
theme = "kanagawa-dragon"  # doesn't matter, we override in CSS anyway

# [extra]
# Put all your custom variables here

[extra.taxonomies.category]
procedural-generation = { title = "Procedural Generation" }
kde = { title = "KDE" }
kernel = { title = "Kernel" }
